import os
import httpx
import structlog
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import RedirectResponse, FileResponse, StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
from backend.config import get_settings
from backend.database import get_db
from backend.schemas.report import ReportResponse
from backend.services.job_service import get_job, get_user_jobs

logger = structlog.get_logger(__name__)
settings = get_settings()

router = APIRouter(tags=["Reports"])

@router.get("/reports/user/{user_id}", response_model=List[ReportResponse])
async def get_user_reports(user_id: str, db: AsyncSession = Depends(get_db)):
    """
    Retrieves all analysis reports generated by a specific user.
    """
    jobs = await get_user_jobs(db, user_id)
    reports = []
    for job in jobs:
        pdf_url = job.pdf_url
        if settings.ENVIRONMENT == "production" or (pdf_url and not pdf_url.startswith("http")):
            pdf_url = f"https://res.cloudinary.com/{settings.CLOUDINARY_CLOUD_NAME}/image/upload/startup_reports/report_{job.id}.pdf"
        reports.append(
            ReportResponse(
                job_id=str(job.id),
                startup_idea=job.startup_idea,
                created_at=job.created_at,
                market_research=job.market_research,
                competitor_analysis=job.competitor_analysis,
                business_strategy=job.business_strategy,
                financials=job.financials,
                swot=job.swot,
                pitch_deck=job.pitch_deck,
                pdf_url=pdf_url
            )
        )
    return reports

@router.get("/report/{job_id}", response_model=ReportResponse)
async def get_report(job_id: str, db: AsyncSession = Depends(get_db)):
    """
    Returns the complete structured JSON analysis results for a completed job.
    """
    job = await get_job(db, job_id)
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Analysis job not found."
        )
        
    if job.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Analysis is not complete. Current status: {job.status}"
        )
        
    pdf_url = job.pdf_url
    if settings.ENVIRONMENT == "production" or (pdf_url and not pdf_url.startswith("http")):
        pdf_url = f"https://res.cloudinary.com/{settings.CLOUDINARY_CLOUD_NAME}/image/upload/startup_reports/report_{job_id}.pdf"

    return ReportResponse(
        job_id=str(job.id),
        startup_idea=job.startup_idea,
        created_at=job.created_at,
        market_research=job.market_research,
        competitor_analysis=job.competitor_analysis,
        business_strategy=job.business_strategy,
        financials=job.financials,
        swot=job.swot,
        pitch_deck=job.pitch_deck,
        pdf_url=pdf_url
    )


@router.get("/report/{job_id}/download")
async def download_report(job_id: str, db: AsyncSession = Depends(get_db)):
    """
    Streams the compiled PDF file. If hosted on Cloudinary, redirects to the URL.
    Otherwise streams a locally cached copy.
    """
    job = await get_job(db, job_id)
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Job not found"
        )
        
    if not job.pdf_url:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="PDF report is not generated yet."
        )
        
    # Local cache check first
    local_pdf = os.path.join(settings.REPORTS_DIR, f"report_{job_id}.pdf")
    if os.path.exists(local_pdf):
        logger.info("Serving PDF from local cache", path=local_pdf)
        return FileResponse(
            path=local_pdf,
            media_type="application/pdf",
            filename=f"startup_report_{job_id}.pdf"
        )
        
    # Remote fallback (Cloudinary / S3)
    if job.pdf_url.startswith("http://") or job.pdf_url.startswith("https://"):
        logger.info("Redirecting download to Cloudinary URL", url=job.pdf_url)
        return RedirectResponse(url=job.pdf_url)
        
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Report PDF file could not be retrieved."
    )
